### ISSUE TITLE
is there an easy way to reset password?

### ISSUE THREAD

**Issue by pejotigrek** [TheCrypt0/yi-hack-v4#224]
ok, so I was stupid enough, not to add the password to my KeePass database, and after flashing/configuring camera weeks ago, I left it in the drawer to wait for the day I'll be installing it in renovated room. today is that day and guess what - I can't login, because I don't remember the password... camera connects to my wifi, so it is configured correctly.

can I reset the password without reflashing? or even reflash won't help?

**Comment by TheCrypt0** [comment]
Hi,
Re-flashing will help, to do so you will have to download an older version
of the firmware, flash it and then re-flash the latest version. This is
needed because the camera detects if you are trying to flash the same
version and prevents it.

Another way could be to attach via UART to the camera and (if the autologin
is enabled) change the password from there. But I'm sure it's easier to
re-flash ;)

**Comment by pejotigrek** [comment]
so reflash it is :)

thank you for such a quick response!
