### ISSUE TITLE
Yi Home EU22 (YR-113-IR) support

### ISSUE THREAD

**Issue by erykosky** [TheCrypt0/yi-hack-v4#26]
Firmwares yi-hack-v3 and v4 doesn't support this version of Yi camera. I only found one firmware that supports YR-113 do you can look into this firmware and adopt it to yours?

https://github.com/npetrovski/yi-hack-easy

**Comment by andrixxxx** [comment]
check your serial number should start with 17CN / 27US / 47US

**Comment by erykosky** [comment]
My serials starts with 22EU

**Comment by xvolte** [comment]
same for me.
i guess we need to wait for @TheCrypt0  answer!

**Comment by TheCrypt0** [comment]
Hi @erykosky,
I had a look at that firmware. It seems like your version runs on an Hi3518eV100 (this hack currently supports the V200 only). However I think that an implementation may be possible.

Unfortunately @npetrovski did not publish the procedure on how to compile its firmware and pack it.

Plus, I'd need to have one camera of that particular model on hands.

Temporarily closing because of lack of documentation about the other firmware. If you manage to get in contact with him and get the all required steps to create it feel free to re-open the issue.
